name = "yas-panel"
main = "_worker.js"
compatibility_date = "2026-01-01"
keep_vars = true

# اضافه کردن KV
[[kv_namespaces]]
binding = "KV"
id = "YOUR_KV_ID_HERE"  # از مرحله بعد دریافت می‌شود
